### ISSUE TITLE
can't find lodash in nova 4

### ISSUE THREAD

**Issue by salomonsanz** [degecko/nova-filters-summary#5]
runtime-core.esm-bundler.js:226 ReferenceError: _ is not defined
    at nova-filters-summary:54:22
    at Array.map (<anonymous>)
    at Proxy.getActiveFilters (nova-filters-summary:53:10)
    at Proxy.created (nova-filters-summary:117:10)
    at en (runtime-core.esm-bundler.js:155:36)
    at tn (runtime-core.esm-bundler.js:164:21)
    at tn (runtime-core.esm-bundler.js:174:21)
    at Wr (runtime-core.esm-bundler.js:2965:5)
    at $r (runtime-core.esm-bundler.js:2867:9)
    at $o (runtime-core.esm-bundler.js:7170:9)

**Comment by adriandmitroca** [comment]
Experiencing the same issue with latest Nova (4.15.1). Potential breaking change in some of Nova updates?

**Comment by degecko** [comment]
Sorry for the late reply.

I'm not entirely sure why you're getting this error. I'm using it successfully with the most recent version as it is.

I would say that a quick fix would be to install lodash yourself and compile again.

However, I will update the plugin to remove it as a dependency, since I'm using only one method from it. Should be able to provide the updates in a couple minutes.

**Comment by degecko** [comment]
v2.0.1 is now available which should fix this issue. Simply update the plugin via composer.

**Comment by salomonsanz** [comment]
thanks @degecko
